apiVersion: v1
kind: Secret
metadata:
  name: pqmsg-server-secrets
  namespace: pqmsg
type: Opaque
stringData:
  PQMSG_DATABASE_URL: postgres://pqmsg:change-me@postgres.pqmsg.svc.cluster.local:5432/pqmsg
  PQMSG_RATE_LIMIT_REDIS_URL: redis://redis.pqmsg.svc.cluster.local:6379/
  PQMSG_FCM_SERVER_KEY: replace-with-fcm-server-key
  PQMSG_SENTRY_DSN: https://public@example.ingest.sentry.io/project-id
