apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pqmsg-server.fullname" . }}-secret
  labels:
    {{- include "pqmsg-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
