[package]
name = "pqmsg-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aes-gcm.workspace = true
argon2.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
hkdf.workspace = true
rand_core.workspace = true
secrecy.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
x25519-dalek.workspace = true
zeroize.workspace = true
oqs = { version = "0.11", default-features = false, features = ["vendored", "ml_kem", "kyber"], optional = true }
cryptoki = { version = "0.7", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }
serde_json = { version = "1", optional = true }

[features]
default = ["pq-oqs"]
pq-oqs = ["dep:oqs"]
fips = ["pq-oqs"]
classical-only-INSECURE = []
hsm-pkcs11 = ["dep:cryptoki"]
wasm = ["classical-only-INSECURE", "dep:wasm-bindgen", "dep:serde-wasm-bindgen", "dep:getrandom", "dep:serde_json"]

[dev-dependencies]
rand.workspace = true
rand_chacha = "0.3"
criterion = { version = "0.5", features = ["html_reports"] }
serde_json = "1"
hex = "0.4"

[[bench]]
name = "crypto_benchmarks"
harness = false
